// Copyright 2024 IBN Network (ICTU Blockchain Network)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
`

func (q *Queries) CountAuditLogs(ctx context.Context, db DBTX) (int64, error) {
	row := db.QueryRow(ctx, countAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditLogsByUser = `-- name: CountAuditLogsByUser :one
SELECT COUNT(*) FROM audit_logs WHERE user_id = $1
`

func (q *Queries) CountAuditLogsByUser(ctx context.Context, db DBTX, userID pgtype.UUID) (int64, error) {
	row := db.QueryRow(ctx, countAuditLogsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    user_id, 
    api_key_id, 
    action, 
    resource_type, 
    resource_id, 
    tx_id, 
    status, 
    details, 
    ip_address, 
    user_agent
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, api_key_id, action, resource_type, resource_id, tx_id, status, details, ip_address, user_agent, created_at
`

type CreateAuditLogParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	ApiKeyID     pgtype.UUID `json:"api_key_id"`
	Action       string      `json:"action"`
	ResourceType pgtype.Text `json:"resource_type"`
	ResourceID   pgtype.Text `json:"resource_id"`
	TxID         pgtype.Text `json:"tx_id"`
	Status       string      `json:"status"`
	Details      []byte      `json:"details"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, db DBTX, arg CreateAuditLogParams) (AuditLog, error) {
	row := db.QueryRow(ctx, createAuditLog,
		arg.UserID,
		arg.ApiKeyID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.TxID,
		arg.Status,
		arg.Details,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiKeyID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.TxID,
		&i.Status,
		&i.Details,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldAuditLogs = `-- name: DeleteOldAuditLogs :exec
DELETE FROM audit_logs
WHERE created_at < $1
`

func (q *Queries) DeleteOldAuditLogs(ctx context.Context, db DBTX, createdAt pgtype.Timestamptz) error {
	_, err := db.Exec(ctx, deleteOldAuditLogs, createdAt)
	return err
}

const getAuditLog = `-- name: GetAuditLog :one
SELECT id, user_id, api_key_id, action, resource_type, resource_id, tx_id, status, details, ip_address, user_agent, created_at FROM audit_logs WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAuditLog(ctx context.Context, db DBTX, id int64) (AuditLog, error) {
	row := db.QueryRow(ctx, getAuditLog, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiKeyID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.TxID,
		&i.Status,
		&i.Details,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLogsByDateRange = `-- name: GetAuditLogsByDateRange :many
SELECT id, user_id, api_key_id, action, resource_type, resource_id, tx_id, status, details, ip_address, user_agent, created_at FROM audit_logs
WHERE created_at >= $1 AND created_at <= $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetAuditLogsByDateRangeParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
}

func (q *Queries) GetAuditLogsByDateRange(ctx context.Context, db DBTX, arg GetAuditLogsByDateRangeParams) ([]AuditLog, error) {
	rows, err := db.Query(ctx, getAuditLogsByDateRange,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApiKeyID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.TxID,
			&i.Status,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, api_key_id, action, resource_type, resource_id, tx_id, status, details, ip_address, user_agent, created_at FROM audit_logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, db DBTX, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApiKeyID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.TxID,
			&i.Status,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByAction = `-- name: ListAuditLogsByAction :many
SELECT id, user_id, api_key_id, action, resource_type, resource_id, tx_id, status, details, ip_address, user_agent, created_at FROM audit_logs
WHERE action = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByActionParams struct {
	Action string `json:"action"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListAuditLogsByAction(ctx context.Context, db DBTX, arg ListAuditLogsByActionParams) ([]AuditLog, error) {
	rows, err := db.Query(ctx, listAuditLogsByAction, arg.Action, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApiKeyID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.TxID,
			&i.Status,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByTxID = `-- name: ListAuditLogsByTxID :many
SELECT id, user_id, api_key_id, action, resource_type, resource_id, tx_id, status, details, ip_address, user_agent, created_at FROM audit_logs
WHERE tx_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAuditLogsByTxID(ctx context.Context, db DBTX, txID pgtype.Text) ([]AuditLog, error) {
	rows, err := db.Query(ctx, listAuditLogsByTxID, txID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApiKeyID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.TxID,
			&i.Status,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByUser = `-- name: ListAuditLogsByUser :many
SELECT id, user_id, api_key_id, action, resource_type, resource_id, tx_id, status, details, ip_address, user_agent, created_at FROM audit_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListAuditLogsByUser(ctx context.Context, db DBTX, arg ListAuditLogsByUserParams) ([]AuditLog, error) {
	rows, err := db.Query(ctx, listAuditLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApiKeyID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.TxID,
			&i.Status,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
