// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	KeyHash     string             `json:"key_hash"`
	Name        pgtype.Text        `json:"name"`
	Permissions []byte             `json:"permissions"`
	RateLimit   pgtype.Int4        `json:"rate_limit"`
	IsActive    pgtype.Bool        `json:"is_active"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Description pgtype.Text        `json:"description"`
	AllowedIps  []netip.Addr       `json:"allowed_ips"`
}

type AuditLog struct {
	ID           int64              `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	ApiKeyID     pgtype.UUID        `json:"api_key_id"`
	Action       string             `json:"action"`
	ResourceType pgtype.Text        `json:"resource_type"`
	ResourceID   pgtype.Text        `json:"resource_id"`
	TxID         pgtype.Text        `json:"tx_id"`
	Status       string             `json:"status"`
	Details      []byte             `json:"details"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type BatchAnalytic struct {
	BatchID           string             `json:"batch_id"`
	FarmLocation      pgtype.Text        `json:"farm_location"`
	Status            pgtype.Text        `json:"status"`
	Owner             pgtype.Text        `json:"owner"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	VerifiedAt        pgtype.Timestamptz `json:"verified_at"`
	VerificationCount pgtype.Int4        `json:"verification_count"`
	QueryCount        pgtype.Int4        `json:"query_count"`
	LastQueriedAt     pgtype.Timestamptz `json:"last_queried_at"`
	Metadata          []byte             `json:"metadata"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	IpAddress        *netip.Addr        `json:"ip_address"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	MspID        string             `json:"msp_id"`
	Role         string             `json:"role"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
