// Copyright 2024 IBN Network (ICTU Blockchain Network)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AclPermission struct {
	ID           pgtype.UUID      `json:"id"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	ResourceType string           `json:"resource_type"`
	Action       string           `json:"action"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type AclPolicy struct {
	ID              pgtype.UUID      `json:"id"`
	Name            string           `json:"name"`
	Description     pgtype.Text      `json:"description"`
	ResourceType    string           `json:"resource_type"`
	ResourcePattern pgtype.Text      `json:"resource_pattern"`
	Actions         []string         `json:"actions"`
	Conditions      []byte           `json:"conditions"`
	Priority        pgtype.Int4      `json:"priority"`
	IsActive        bool             `json:"is_active"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type ApiKey struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	KeyHash     string             `json:"key_hash"`
	Name        pgtype.Text        `json:"name"`
	Permissions []byte             `json:"permissions"`
	IsActive    pgtype.Bool        `json:"is_active"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Description pgtype.Text        `json:"description"`
}

type AuditLog struct {
	ID           int64              `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	ApiKeyID     pgtype.UUID        `json:"api_key_id"`
	Action       string             `json:"action"`
	ResourceType pgtype.Text        `json:"resource_type"`
	ResourceID   pgtype.Text        `json:"resource_id"`
	TxID         pgtype.Text        `json:"tx_id"`
	Status       string             `json:"status"`
	Details      []byte             `json:"details"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type BatchAnalytic struct {
	BatchID           string             `json:"batch_id"`
	FarmLocation      pgtype.Text        `json:"farm_location"`
	Status            pgtype.Text        `json:"status"`
	Owner             pgtype.Text        `json:"owner"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	VerifiedAt        pgtype.Timestamptz `json:"verified_at"`
	VerificationCount pgtype.Int4        `json:"verification_count"`
	QueryCount        pgtype.Int4        `json:"query_count"`
	LastQueriedAt     pgtype.Timestamptz `json:"last_queried_at"`
	Metadata          []byte             `json:"metadata"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Block struct {
	ID               int64            `json:"id"`
	Number           int64            `json:"number"`
	Hash             string           `json:"hash"`
	PreviousHash     pgtype.Text      `json:"previous_hash"`
	DataHash         pgtype.Text      `json:"data_hash"`
	TransactionCount pgtype.Int4      `json:"transaction_count"`
	ChannelName      string           `json:"channel_name"`
	Timestamp        pgtype.Timestamp `json:"timestamp"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type EventSubscription struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	ApiKeyID      pgtype.UUID      `json:"api_key_id"`
	Name          string           `json:"name"`
	Type          string           `json:"type"`
	ChannelName   string           `json:"channel_name"`
	ChaincodeName pgtype.Text      `json:"chaincode_name"`
	EventName     pgtype.Text      `json:"event_name"`
	WebhookUrl    pgtype.Text      `json:"webhook_url"`
	WebhookSecret pgtype.Text      `json:"webhook_secret"`
	Filters       []byte           `json:"filters"`
	Active        bool             `json:"active"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	TokenHash string           `json:"token_hash"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	IsRevoked pgtype.Bool      `json:"is_revoked"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	RevokedAt pgtype.Timestamp `json:"revoked_at"`
}

type RolePermission struct {
	ID        pgtype.UUID      `json:"id"`
	Role      string           `json:"role"`
	PolicyID  pgtype.UUID      `json:"policy_id"`
	GrantedBy pgtype.UUID      `json:"granted_by"`
	GrantedAt pgtype.Timestamp `json:"granted_at"`
}

type Session struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	IpAddress        *netip.Addr        `json:"ip_address"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID            pgtype.UUID      `json:"id"`
	TxID          string           `json:"tx_id"`
	ChannelName   string           `json:"channel_name"`
	ChaincodeName string           `json:"chaincode_name"`
	FunctionName  string           `json:"function_name"`
	Args          []byte           `json:"args"`
	TransientData []byte           `json:"transient_data"`
	UserID        pgtype.UUID      `json:"user_id"`
	ApiKeyID      pgtype.UUID      `json:"api_key_id"`
	Status        string           `json:"status"`
	BlockNumber   pgtype.Int8      `json:"block_number"`
	BlockHash     pgtype.Text      `json:"block_hash"`
	Timestamp     pgtype.Timestamp `json:"timestamp"`
	ErrorMessage  pgtype.Text      `json:"error_message"`
	EndorsingOrgs []string         `json:"endorsing_orgs"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type TransactionStatusHistory struct {
	ID            pgtype.UUID      `json:"id"`
	TransactionID pgtype.UUID      `json:"transaction_id"`
	Status        string           `json:"status"`
	BlockNumber   pgtype.Int8      `json:"block_number"`
	Timestamp     pgtype.Timestamp `json:"timestamp"`
	Details       []byte           `json:"details"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	MspID        string             `json:"msp_id"`
	Role         string             `json:"role"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserPermission struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	PolicyID  pgtype.UUID      `json:"policy_id"`
	GrantedBy pgtype.UUID      `json:"granted_by"`
	GrantedAt pgtype.Timestamp `json:"granted_at"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	IsActive  bool             `json:"is_active"`
}

type WebhookDelivery struct {
	ID             pgtype.UUID      `json:"id"`
	SubscriptionID pgtype.UUID      `json:"subscription_id"`
	EventID        string           `json:"event_id"`
	WebhookUrl     string           `json:"webhook_url"`
	Payload        []byte           `json:"payload"`
	Status         string           `json:"status"`
	StatusCode     pgtype.Int4      `json:"status_code"`
	ResponseBody   pgtype.Text      `json:"response_body"`
	ErrorMessage   pgtype.Text      `json:"error_message"`
	Attempts       int32            `json:"attempts"`
	DeliveredAt    pgtype.Timestamp `json:"delivered_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type WebsocketConnection struct {
	ID             pgtype.UUID      `json:"id"`
	SubscriptionID pgtype.UUID      `json:"subscription_id"`
	ConnectionID   string           `json:"connection_id"`
	UserID         pgtype.UUID      `json:"user_id"`
	IpAddress      pgtype.Text      `json:"ip_address"`
	UserAgent      pgtype.Text      `json:"user_agent"`
	ConnectedAt    pgtype.Timestamp `json:"connected_at"`
	DisconnectedAt pgtype.Timestamp `json:"disconnected_at"`
	LastPingAt     pgtype.Timestamp `json:"last_ping_at"`
}
