// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAPIKeysByUser(ctx context.Context, db DBTX, userID pgtype.UUID) (int64, error)
	CountAuditLogs(ctx context.Context, db DBTX) (int64, error)
	CountAuditLogsByUser(ctx context.Context, db DBTX, userID pgtype.UUID) (int64, error)
	CountUsers(ctx context.Context, db DBTX) (int64, error)
	CreateAPIKey(ctx context.Context, db DBTX, arg CreateAPIKeyParams) (ApiKey, error)
	CreateAuditLog(ctx context.Context, db DBTX, arg CreateAuditLogParams) (AuditLog, error)
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (User, error)
	DeleteAPIKey(ctx context.Context, db DBTX, id pgtype.UUID) error
	DeleteAPIKeysByUser(ctx context.Context, db DBTX, userID pgtype.UUID) error
	DeleteOldAuditLogs(ctx context.Context, db DBTX, createdAt pgtype.Timestamptz) error
	DeleteUser(ctx context.Context, db DBTX, id pgtype.UUID) error
	GetAPIKey(ctx context.Context, db DBTX, id pgtype.UUID) (ApiKey, error)
	GetAPIKeyByHash(ctx context.Context, db DBTX, keyHash string) (ApiKey, error)
	GetActiveAPIKeys(ctx context.Context, db DBTX) ([]ApiKey, error)
	GetAuditLog(ctx context.Context, db DBTX, id int64) (AuditLog, error)
	GetAuditLogsByDateRange(ctx context.Context, db DBTX, arg GetAuditLogsByDateRangeParams) ([]AuditLog, error)
	GetUser(ctx context.Context, db DBTX, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, db DBTX, email string) (User, error)
	GetUsersByMSP(ctx context.Context, db DBTX, mspID string) ([]User, error)
	GetUsersByRole(ctx context.Context, db DBTX, role string) ([]User, error)
	ListAPIKeys(ctx context.Context, db DBTX, userID pgtype.UUID) ([]ApiKey, error)
	ListAuditLogs(ctx context.Context, db DBTX, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByAction(ctx context.Context, db DBTX, arg ListAuditLogsByActionParams) ([]AuditLog, error)
	ListAuditLogsByTxID(ctx context.Context, db DBTX, txID pgtype.Text) ([]AuditLog, error)
	ListAuditLogsByUser(ctx context.Context, db DBTX, arg ListAuditLogsByUserParams) ([]AuditLog, error)
	ListUsers(ctx context.Context, db DBTX, arg ListUsersParams) ([]User, error)
	UpdateAPIKey(ctx context.Context, db DBTX, arg UpdateAPIKeyParams) (ApiKey, error)
	UpdateAPIKeyLastUsed(ctx context.Context, db DBTX, id pgtype.UUID) error
	UpdateUser(ctx context.Context, db DBTX, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
