// Copyright 2024 IBN Network (ICTU Blockchain Network)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddTransactionStatusHistory(ctx context.Context, db DBTX, arg AddTransactionStatusHistoryParams) (TransactionStatusHistory, error)
	CountAPIKeysByUser(ctx context.Context, db DBTX, userID pgtype.UUID) (int64, error)
	CountAuditLogs(ctx context.Context, db DBTX) (int64, error)
	CountAuditLogsByUser(ctx context.Context, db DBTX, userID pgtype.UUID) (int64, error)
	CountEventSubscriptions(ctx context.Context, db DBTX, arg CountEventSubscriptionsParams) (int64, error)
	CountTransactions(ctx context.Context, db DBTX, arg CountTransactionsParams) (int64, error)
	CountUsers(ctx context.Context, db DBTX) (int64, error)
	CreateAPIKey(ctx context.Context, db DBTX, arg CreateAPIKeyParams) (ApiKey, error)
	CreateAuditLog(ctx context.Context, db DBTX, arg CreateAuditLogParams) (AuditLog, error)
	CreateEventSubscription(ctx context.Context, db DBTX, arg CreateEventSubscriptionParams) (EventSubscription, error)
	// Refresh Token queries only (API Key queries are in api_keys.sql)
	CreateRefreshToken(ctx context.Context, db DBTX, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateTransaction(ctx context.Context, db DBTX, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (User, error)
	CreateWebSocketConnection(ctx context.Context, db DBTX, arg CreateWebSocketConnectionParams) (WebsocketConnection, error)
	CreateWebhookDelivery(ctx context.Context, db DBTX, arg CreateWebhookDeliveryParams) (WebhookDelivery, error)
	DeleteAPIKey(ctx context.Context, db DBTX, id pgtype.UUID) error
	DeleteAPIKeysByUser(ctx context.Context, db DBTX, userID pgtype.UUID) error
	DeleteEventSubscription(ctx context.Context, db DBTX, id pgtype.UUID) error
	DeleteExpiredRefreshTokens(ctx context.Context, db DBTX) error
	DeleteOldAuditLogs(ctx context.Context, db DBTX, createdAt pgtype.Timestamptz) error
	DeleteUser(ctx context.Context, db DBTX, id pgtype.UUID) error
	DeleteWebSocketConnection(ctx context.Context, db DBTX, id pgtype.UUID) error
	GetAPIKey(ctx context.Context, db DBTX, id pgtype.UUID) (ApiKey, error)
	GetAPIKeyByHash(ctx context.Context, db DBTX, keyHash string) (ApiKey, error)
	GetActiveAPIKeys(ctx context.Context, db DBTX) ([]ApiKey, error)
	GetActiveSubscriptionsByChannelAndChaincode(ctx context.Context, db DBTX, arg GetActiveSubscriptionsByChannelAndChaincodeParams) ([]EventSubscription, error)
	GetAuditLog(ctx context.Context, db DBTX, id int64) (AuditLog, error)
	GetAuditLogsByDateRange(ctx context.Context, db DBTX, arg GetAuditLogsByDateRangeParams) ([]AuditLog, error)
	GetEventSubscriptionByID(ctx context.Context, db DBTX, id pgtype.UUID) (EventSubscription, error)
	GetRefreshToken(ctx context.Context, db DBTX, tokenHash string) (RefreshToken, error)
	GetTransactionByID(ctx context.Context, db DBTX, id pgtype.UUID) (Transaction, error)
	GetTransactionByTxID(ctx context.Context, db DBTX, txID string) (Transaction, error)
	GetTransactionStatusHistory(ctx context.Context, db DBTX, transactionID pgtype.UUID) ([]TransactionStatusHistory, error)
	GetUser(ctx context.Context, db DBTX, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, db DBTX, email string) (User, error)
	// Note: username column will be available after migration 000002
	// For now, search by email only. After migration, uncomment: WHERE username = $1 OR email = $1
	GetUserByUsernameOrEmail(ctx context.Context, db DBTX, email string) (User, error)
	GetUsersByMSP(ctx context.Context, db DBTX, mspID string) ([]User, error)
	GetUsersByRole(ctx context.Context, db DBTX, role string) ([]User, error)
	GetWebSocketConnectionByConnectionID(ctx context.Context, db DBTX, connectionID string) (WebsocketConnection, error)
	GetWebSocketConnectionByID(ctx context.Context, db DBTX, id pgtype.UUID) (WebsocketConnection, error)
	ListAPIKeys(ctx context.Context, db DBTX, userID pgtype.UUID) ([]ApiKey, error)
	ListAuditLogs(ctx context.Context, db DBTX, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByAction(ctx context.Context, db DBTX, arg ListAuditLogsByActionParams) ([]AuditLog, error)
	ListAuditLogsByTxID(ctx context.Context, db DBTX, txID pgtype.Text) ([]AuditLog, error)
	ListAuditLogsByUser(ctx context.Context, db DBTX, arg ListAuditLogsByUserParams) ([]AuditLog, error)
	ListEventSubscriptions(ctx context.Context, db DBTX, arg ListEventSubscriptionsParams) ([]EventSubscription, error)
	ListTransactions(ctx context.Context, db DBTX, arg ListTransactionsParams) ([]Transaction, error)
	ListUsers(ctx context.Context, db DBTX, arg ListUsersParams) ([]User, error)
	ListWebSocketConnections(ctx context.Context, db DBTX, subscriptionID pgtype.UUID) ([]WebsocketConnection, error)
	ListWebhookDeliveries(ctx context.Context, db DBTX, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error)
	RevokeAllUserRefreshTokens(ctx context.Context, db DBTX, userID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, db DBTX, tokenHash string) error
	UpdateAPIKey(ctx context.Context, db DBTX, arg UpdateAPIKeyParams) (ApiKey, error)
	UpdateAPIKeyLastUsed(ctx context.Context, db DBTX, id pgtype.UUID) error
	UpdateEventSubscription(ctx context.Context, db DBTX, arg UpdateEventSubscriptionParams) (EventSubscription, error)
	UpdateTransactionStatus(ctx context.Context, db DBTX, arg UpdateTransactionStatusParams) (Transaction, error)
	UpdateUser(ctx context.Context, db DBTX, arg UpdateUserParams) (User, error)
	UpdateWebSocketConnection(ctx context.Context, db DBTX, arg UpdateWebSocketConnectionParams) (WebsocketConnection, error)
	UpdateWebhookDelivery(ctx context.Context, db DBTX, arg UpdateWebhookDeliveryParams) (WebhookDelivery, error)
}

var _ Querier = (*Queries)(nil)
